CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -g
TARGET = pvv_solver

SRC = main.c \
      graph.c \
      memory_manager.c \
      file_reader.c \
      command_parser.c \
      interface.c \
      hamiltonian.c \
      graph_utils.c \
      tsp_solver.c \
      path_finder.c

OBJ = $(SRC:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)

run: $(TARGET)
	./$(TARGET)

valgrind: $(TARGET)
	valgrind --leak-check=full ./$(TARGET)

.PHONY: all clean run valgrind